# Generated by Django 2.0.6 on 2018-07-09 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DovizCevirici', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={'verbose_name_plural': 'Kayıt Ol & Kayıt Listesi'},
        ),
    ]
