# Generated by Django 2.0.6 on 2018-07-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DovizCevirici', '0002_auto_20180710_0214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsorlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_ad', models.CharField(blank=True, max_length=255)),
                ('sponsor_foto', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
