# Generated by Django 2.0.6 on 2018-07-12 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DovizCevirici', '0003_auto_20180712_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='CevirilenParalar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ana_para', models.CharField(max_length=20, verbose_name='Ana Para')),
                ('cevirilen_para', models.CharField(max_length=20, verbose_name='Çevirilen Para')),
                ('sonuc', models.CharField(max_length=20, verbose_name='Sonuç')),
                ('ceviren', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Üye Adı')),
            ],
        ),
    ]
