# Generated by Django 2.0.6 on 2018-07-12 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DovizCevirici', '0004_cevirilenparalar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cevirilenparalar',
            name='ana_para',
            field=models.CharField(max_length=20, null=True, verbose_name='Ana Para'),
        ),
        migrations.AlterField(
            model_name='cevirilenparalar',
            name='ceviren',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Üye Adı'),
        ),
        migrations.AlterField(
            model_name='cevirilenparalar',
            name='cevirilen_para',
            field=models.CharField(max_length=20, null=True, verbose_name='Çevirilen Para'),
        ),
        migrations.AlterField(
            model_name='cevirilenparalar',
            name='sonuc',
            field=models.CharField(max_length=20, null=True, verbose_name='Sonuç'),
        ),
    ]
