# Generated by Django 2.0.6 on 2018-07-12 16:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DovizCevirici', '0005_auto_20180712_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='cevirilenparalar',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Oluşturulma Tarihi'),
            preserve_default=False,
        ),
    ]
