# Generated by Django 2.0.6 on 2018-07-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DovizCevirici', '0006_cevirilenparalar_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cevirilenparalar',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='cevirilenparalar',
            name='sonuc',
            field=models.IntegerField(null=True, verbose_name='Sonuç'),
        ),
    ]
