# Generated by Django 2.0.6 on 2018-07-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DovizCevirici', '0008_auto_20180712_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='cevirilenparalar',
            name='cevirilen_miktar',
            field=models.FloatField(default=50, verbose_name='Çevirilen Miktar'),
            preserve_default=False,
        ),
    ]
